### ISSUE TITLE
Is there a way to get tslint-compatible alphabetical sorting?

### ISSUE THREAD

**Issue by alextreppass** [amatiasq/vsc-sort-imports#12]
Hi, first off - thanks for fixing #5 - I'm trying it out now.

I have the following config in my tslint.json file:
```json
"ordered-imports": [true, {
  "import-sources-order": "case-insensitive",
  "named-imports-order": "case-insensitive"
}],
```

(`ordered-import` rule docs here: https://palantir.github.io/tslint/rules/ordered-imports/)

No configuration in my package.json - it's a shared project and I can't commit IDE-specific settings.

I can't seem to get import-sort to sort files in a manner that tslint is happy with. Am I missing something simple?

In the meantime, I've found `"tslint.autoFixOnSave": true` from the [vscode-tslint](https://github.com/Microsoft/vscode-tslint) seems to do the job automatically.

**Comment by cliffkoh** [comment]
Reading that tslint rule, `"sort-imports.default-sort-style": "module-scoped"` seems like it would be compatible. 

It would be great if you could provide an example of imports sorted by this scheme, that still fails the tslint rule...

**Comment by alextreppass** [comment]
Sure.

ts-lint sorted:
```ts
import { Something } from 'foo_bar/quux';
import { SomethingElse } from 'foo_bar_baz/quux';
```

sort-imports sorted (produces ts lint errors):
```ts
import { SomethingElse } from 'foo_bar_baz/quux';
import { Something } from 'foo_bar/quux';
```

**Comment by cliffkoh** [comment]
Did you change your vscode user settings to add in `"sort-imports.default-sort-style": "module-scoped"`?

If this is not taking effect, there might be an entry in package.json or .importsortrc somewhere...

**Comment by cliffkoh** [comment]
Nevermind, I was able to repro it. Taking a look

**Comment by cliffkoh** [comment]
So this happens because all the module-based sorts are sorting "naturally" (by "en" locale sorting rules).

`"foo_bar".localeCompare("foo/bar", "en") === -1`

which is why we see what we see above.

The TSLint rule is probably using unicode based sorting, in which case `foo/bar` comes before `foo_bar`.

I can make a fix in the upstream dependency, but we would most likely need an update of this extension for the updated upstream dependency to be picked up and packaged (and published).

**Comment by alextreppass** [comment]
Ah yep, that makes sense. Thanks for digging into it 👍 

No rush here - vscode-tslint with autoFixOnSave works well enough in the meantime.

**Comment by cliffkoh** [comment]
@amatiasq Updated import-sort-style-module-scoped to 1.0.3 that sorts by unicode, that should fix the issue here. Will need to update the dependency and repackage/publish.

**Comment by amatiasq** [comment]
@cliffkoh Thanks! That was a quick reaction. I'll publish another minor in a few hours.

**Comment by cliffkoh** [comment]
@amatiasq Sure. :)

**Comment by amatiasq** [comment]
A new version has been released with the fix, thanks for your patience.

@cliffkoh please contact me at amatiasq@gmail.com, I need your Microsoft account email to add you as a publisher.

**Comment by gfpacheco** [comment]
I'm sorry, but it's still not sorting alphabetically for me, I tried module-compact as well but it sort my imports like this:

```
import React from 'react';
import styled from '@emotion/styled';
```

Instead of what tslint expects:

```
import styled from '@emotion/styled';
import React from 'react';
```
